#!/bin/bash

if [ $1 == "-install" ]; then
    sudo yum install -y docker-engine
    sudo systemctl enable docker
    sudo systemctl start docker
fi

docker build -t fedora23-systemd ./systemd-fedora/
docker build -t labs-proxy-embed ./labs-proxy/
docker build -t labs-rails ./labs-rails/
docker build -t labs-nodejs ./labs-node/
docker build -t labs-mysql ./labs-mysql/
# docker pull mongo
docker build -t labs-mongo ./labs-mongo/
