#!/bin/bash

if [ $1 == "-install" ]; then
    sudo yum install -y docker-engine
    sudo systemctl enable docker
    sudo systemctl start docker
fi

docker build -t fedora23-systemd /data/dockerfiles/systemd-fedora/
docker build -t labs-proxy-embed /data/dockerfiles/labs-proxy/
docker build -t labs-rails /data/dockerfiles/labs-rails/
docker build -t labs-nodejs /data/dockerfiles/labs-node/
docker build -t labs-mysql /data/dockerfiles/labs-mysql/
# docker pull mongo
docker build -t labs-mongo /data/dockerfiles/labs-mongo/