#!/bin/bash

echo "create-conf appport proxyport [ci] [https]"
url="https://access.redhat.com"
myHost="my-host-domain"
proxy = "http://"$myHost
paramArray=( "$@" )
appport=$1
proxyport=$2
for param in ${paramArray[@]}; do
  case $param in
     "ci" )
          url="https://access.devgssci.devlab.phx1.redhat.com"
     ;;
     "https" )
          proxy = "https://"$myHost
     ;;
  esac
done
cat >> /etc/httpd/myconf.d/labs.conf << EOF
Listen $proxyport
<VirtualHost *:$proxyport>
     ProxyRequests Off

     SSLEngine On
     SSLProxyEngine On
     SSLProxyVerify none
     SSLProxyCheckPeerCN off
     SSLProxyCheckPeerName off
     SSLCertificateFile /etc/pki/tls/certs/labs.crt
     SSLCertificateKeyFile /etc/pki/tls/private/labs.key

     ServerName localhost.localdomain     

     ProxyPass /webassets/ $url/webassets/
     ProxyPass /chrome_themes/ $url/chrome_themes/
     ProxyPass /services/ $url/services/
     ProxyPass /click/ $url/click/
     ProxyPass /suggest/ $url/suggest/
     ProxyPass /rs/ $url/rs/
     ProxyPass /management/ $url/management/

     ProxyPass /labs/   $proxy:$appport/labs/
</VirtualHost>
EOF

cat /etc/httpd/myconf.d/labs.conf
