#!/bin/bash

paramArray=( "$@" )
if [[ $(echo ${paramArray[@]} | grep -Eao 'db' -q; echo $?) -eq 0 ]]; then
    source /home/labsapp/.bashrc 
    env | grep MONGOLAB_URI
    env | grep NODE_ENV
fi
# nohup accessproxy -l 1337 &
cd /labsapp
if [[ $(echo ${paramArray[@]} | grep -Eao 'install' -q; echo $?) -eq 0 ]]; then
    bower install
    # --allow-root
    npm install
fi
if [[ $(echo ${paramArray[@]} | grep -Eao 'norake' -q; echo $?) -ne 0 ]]; then
    node server/feed.js
fi
if [[ $(echo ${paramArray[@]} | grep -Eao 'local' -q; echo $?) -eq 0 ]]; then
    grunt serve --gruntfile Gruntfile_dev.js --force
else
    echo "----------- not local ---------------"
    grunt serve --force
fi
